#!/usr/bin/env bash
# add_supabase_to_app.sh — Add reserved Supabase API path routes to an existing nginx vhost
# (created by add_app.sh). Proxies to local Kong (Docker).
#
# Usage:
#   sudo ./add_supabase_to_app.sh <server_name>
# Example:
#   sudo ./add_supabase_to_app.sh app.clientdomain.com
#
# Optional env:
#   NGINX_CONF_DIR=/etc/nginx/conf.d
#   SUPABASE_DOCKER_DIR=/opt/supabase/docker   (read KONG_HTTP_PORT from .env)
#   KONG_HTTP_PORT=8000                        (override)
#
set -euo pipefail

NGINX_CONF_DIR="${NGINX_CONF_DIR:-/etc/nginx/conf.d}"
SUPABASE_DOCKER_DIR="${SUPABASE_DOCKER_DIR:-/opt/supabase/docker}"
SNIPPET_PATH="/etc/nginx/snippets/supabase-kong-proxy.conf"
MARKER="bash-scripts-supabase-include"

DOMAIN="${1:-}"
if [[ -z "${DOMAIN}" ]]; then
  read -rp "Nginx server_name (e.g. app.example.com): " DOMAIN
fi
[[ -n "${DOMAIN}" ]] || { echo "server_name is required"; exit 1; }

if [[ $EUID -ne 0 ]]; then echo "Run as root (sudo)"; exit 1; fi

CONF="${NGINX_CONF_DIR}/${DOMAIN}.conf"
[[ -f "${CONF}" ]] || { echo "Missing ${CONF} — run add_app.sh for this host first."; exit 1; }

KONG_HTTP_PORT="${KONG_HTTP_PORT:-}"
if [[ -z "${KONG_HTTP_PORT}" && -f "${SUPABASE_DOCKER_DIR}/.env" ]]; then
  KONG_HTTP_PORT="$(grep -E '^KONG_HTTP_PORT=' "${SUPABASE_DOCKER_DIR}/.env" | cut -d= -f2- | tr -d '\r' || true)"
fi
: "${KONG_HTTP_PORT:=8000}"

write_snippet() {
  # Paths match Supabase Kong routes (see docker/volumes/api/kong.yml).
  cat > "${SNIPPET_PATH}" <<EOF
# Generated by add_supabase_to_app.sh — do not edit by hand; re-run the script to update.
# Kong: 127.0.0.1:${KONG_HTTP_PORT}

  location ^~ /auth/v1 {
    proxy_pass http://127.0.0.1:${KONG_HTTP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    proxy_buffer_size 160k;
    proxy_buffers 64 160k;
    client_max_body_size 52m;
  }

  location ^~ /rest/v1 {
    proxy_pass http://127.0.0.1:${KONG_HTTP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    proxy_buffer_size 160k;
    proxy_buffers 64 160k;
    client_max_body_size 52m;
  }

  location ^~ /graphql/v1 {
    proxy_pass http://127.0.0.1:${KONG_HTTP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_buffer_size 160k;
    proxy_buffers 64 160k;
    client_max_body_size 52m;
  }

  location ^~ /realtime/v1 {
    proxy_pass http://127.0.0.1:${KONG_HTTP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    proxy_buffer_size 160k;
    proxy_buffers 64 160k;
  }

  location ^~ /storage/v1 {
    proxy_pass http://127.0.0.1:${KONG_HTTP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    proxy_buffer_size 160k;
    proxy_buffers 64 160k;
    client_max_body_size 52m;
  }

  location ^~ /functions/v1 {
    proxy_pass http://127.0.0.1:${KONG_HTTP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
    proxy_buffer_size 160k;
    proxy_buffers 64 160k;
    client_max_body_size 52m;
  }

  location = /.well-known/oauth-authorization-server {
    proxy_pass http://127.0.0.1:${KONG_HTTP_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
  }
EOF
}

ensure_map_directive() {
  # WebSocket Connection header: upgrade when client sends Upgrade, else close.
  local maps="/etc/nginx/conf.d/00-bash-scripts-ws-map.conf"
  if [[ -f "${maps}" ]] && grep -q 'map \$http_upgrade \$connection_upgrade' "${maps}"; then
    return 0
  fi
  cat > "${maps}" <<'MAPEOF'
# Shared by add_app-style vhosts and Supabase path proxy (bash-scripts)
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
MAPEOF
}

insert_include_into_conf() {
  local conf="$1"
  local domain="$2"
  python3 - "$conf" "$domain" "$MARKER" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
domain = sys.argv[2]
marker = sys.argv[3]
text = path.read_text(encoding="utf-8")

if "supabase-kong-proxy.conf" in text:
    print(f"Include already present (snippet refreshed): {path}")
    sys.exit(0)

include_line = f"  include /etc/nginx/snippets/supabase-kong-proxy.conf;  # {marker}\n"
# Match server_name lines that include this host (covers certbot :80 and :443 blocks)
pat = re.compile(
    r"^(\s*server_name\s+[^;\n]*" + re.escape(domain) + r"[^;\n]*;)\s*$",
    re.MULTILINE | re.IGNORECASE,
)
new_text, n = pat.subn(lambda m: m.group(1) + "\n" + include_line, text)
if n == 0:
    print(f"ERROR: No server_name line containing '{domain}' in {path}", file=sys.stderr)
    sys.exit(1)
path.write_text(new_text, encoding="utf-8")
print(f"Inserted Supabase include after {n} server_name line(s): {path}")
PY
}

write_snippet
ensure_map_directive
cp -a "${CONF}" "${CONF}.bak.$(date +%Y%m%d%H%M%S)"
insert_include_into_conf "${CONF}" "${DOMAIN}"

# Preserve webhook paths (unchanged) — they use ^~ and stay in vhost; snippet uses ^~ for API paths.
# Order: nginx chooses longest prefix; ^~ stops search. /auth/v1 etc. win over / for those prefixes.

nginx -t
systemctl reload nginx

echo ""
echo "=========================================="
echo "Supabase path routing added for: ${DOMAIN}"
echo "=========================================="
echo "Config:        ${CONF}"
echo "Snippet:       ${SNIPPET_PATH}"
echo "Kong upstream: 127.0.0.1:${KONG_HTTP_PORT}"
echo ""
echo "Set app env to:"
echo "  NEXT_PUBLIC_SUPABASE_URL=https://${DOMAIN}"
echo "  (use http only if this vhost is HTTP-only — match install_supabase.sh PUBLIC_BASE_URL)"
echo "=========================================="
